language: node_js
node_js:
  - "12"
cache: yarn

install: yarn
script:
  - echo "Not found tests"

jobs:
  include:
    - stage: deploy
      script:
        - npm install netlify-cli -g
        - yarn bootstrap
        - yarn build
        - netlify deploy -s $NETLIFY_SITE_ID -t $NETLIFY_ACCESS_TOKEN -p ./build
    # - stage: docker-deploy
    #   services:
    #     - docker
    #   env:
    #     - IMAGE_NAME=andrelmlins1/react-versus-svelte
    #   script:
    #     - npm install netlify-cli -g
    #     - yarn bootstrap
    #     - yarn build
    #     - docker build --pull --cache-from "${IMAGE_NAME}:latest" --tag "$IMAGE_NAME" .
    #     - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
    #     - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
    #   on:
    #     branch: master
    #   deploy:
    #     provider: script
    #     script: docker push "${IMAGE_NAME}:latest"
    #     on:
    #       branch: master
