language: node_js
node_js:
  - "12"
cache: yarn

install: yarn
script:
  - echo "Not found tests"

jobs:
  include:
    - stage: deploy
      script:
        - npm install netlify-cli -g
        - yarn bootstrap
        - yarn build
        - netlify deploy --site $NETLIFY_SITE_ID --auth $NETLIFY_ACCESS_TOKEN --dir=./build --prod
    - stage: docker-deploy
      env:
        - IMAGE_NAME=andrelmlins1/react-versus-svelte
      script:
        - yarn bootstrap
        - yarn build
        - docker build --pull --cache-from "${IMAGE_NAME}:latest" --tag "$IMAGE_NAME" .
        - docker login -u "$DOCKER_USER" -p "$DOCKER_PASS"
        - docker tag "$IMAGE_NAME" "${IMAGE_NAME}:latest"
      on:
        branch: master
      deploy:
        provider: script
        script: docker push "${IMAGE_NAME}:latest"
        on:
          branch: master
